const Sim = require('./server/data/simulator.js');
const sim = new Sim();
for (let i = 0; i < 10; i++) sim.tick();
const snap = sim.getSnapshot();
console.log('=== 高炉 ===');
snap.blastFurnaces.forEach(bf => console.log('  ' + bf.name + ' 温度=' + bf.hotMetalTemp.toFixed(2) + 'C 风压=' + bf.windPressure.toFixed(1) + 'kPa 硅=' + bf.silicon.toFixed(3)));
console.log('=== 转炉 ===');
snap.converters.forEach(c => console.log('  ' + c.name + ' 温度=' + c.temp.toFixed(1) + 'C 气泡=' + c.bubbleCount + ' 氩气=' + c.argonActive));
console.log('=== 连铸机 ===');
snap.casters.forEach(ct => console.log('  ' + ct.name + ' 拉速=' + ct.castingSpeed.toFixed(2) + 'm/min sigma=' + ct._sigma.toFixed(3) + ' 波动=' + ct.levelVariation.toFixed(2)));
console.log('=== 轧机 ===');
snap.rollingMills.forEach(rm => console.log('  ' + rm.name + ' 轧制力=' + rm.rollingForce.toFixed(0) + ' 偏差=' + rm.thicknessDeviation.toFixed(4)));
console.log('=== 烟囱 ===');
snap.stacks.forEach(st => console.log('  ' + st.name + ' SO2=' + st.so2.toFixed(1) + ' NOx=' + st.nox.toFixed(1) + ' 超限=' + st.overLimit + ' 减排=' + st._reducing));
console.log('=== 能耗 ===');
console.log('  综合能耗: ' + snap.energyConsumption.current.toFixed(1) + ' kgce/t');
snap.energyConsumption.perFurnace.forEach(pf => console.log('  ' + pf.name + ': ' + pf.value.toFixed(1) + ' 负载=' + pf._load.toFixed(3) + ' 效率=' + pf._efficiency.toFixed(3)));
console.log('=== 人员 ===');
snap.personnel.forEach(p => console.log('  ' + p.name + ' x=' + p.x.toFixed(2) + ' z=' + p.z.toFixed(2) + ' v=(' + p.vx.toFixed(3) + ',' + p.vz.toFixed(3) + ') 危险=' + p.inDanger));
console.log('=== 报警 ===');
console.log('  数量: ' + snap.alarms.length);
console.log('=== 产量 ===');
console.log('  产量: ' + snap.dailyStats.production + ' 合格率: ' + snap.dailyStats.passRate.toFixed(2) + '%');
console.log('\nAll 10 ticks OK');
